/** Experimental scene reference labels — delete this file (+ UI wiring) to revert. */
export const MOMENT_LABELS: Record<string, string> = {
  "moment-001": "Title card",
  "moment-002": "Bear's living room — TV romance, Baron on the couch",
  "moment-003": "Bear's kitchen — cat mess on the floor",
  "moment-004": "Bear's bathroom — pills in the medicine cabinet",
  "moment-005": "Bear's living room — cleaning Baron off the carpet",
  "moment-006": "Bear's bedroom — Nicky voicemail, pills on the phone",
  "moment-007": "Bear's bedroom — Bear crying on the bed",
  "moment-008": "Crystal shop — Bear browses, meets Viola",
  "moment-009": "Crystal shop checkout — buys One Wish Willow for Nicky",
  "moment-010": "Bear's car — rehearses Nicky confession for Ian",
  "moment-011": "Trivia bar — friends tell work horror stories",
  "moment-012": "Trivia bar parking lot — Ian pushes karaoke",
  "moment-013": "Bear's car — driving drunk Nicky home",
  "moment-014": "Bear's house — Nicky sees the apartment",
  "moment-015": "Bear's kitchen — “it smells like you”",
  "moment-016": "Bear's bedroom — Nicky in bed, Bear says goodnight",
  "moment-017": "Bear's bedroom — floor bed, middle-of-night bathroom",
  "moment-018": "Bear's bedroom — morning, empty bed",
  "moment-019": "Bear's living room — Nicky cleaned up Baron",
  "moment-020": "Mandy's parking lot — Nicky almost kisses Bear",
  "moment-021": "Mandy's Music — Carter, Ian, and Sarah at the store",
  "moment-022": "Mandy's break room — Ian asks if Bear slept with Nicky",
  "moment-023": "Mandy's parking lot (night) — won't drive Nicky home yet",
  "moment-024": "Bear's living room — Nicky shows up dressed up",
  "moment-025": "Bear's bedroom — almost sex, Nicky snaps awake",
  "moment-026": "Bear's kitchen — happy-couple breakfast montage",
  "moment-027": "Mandy's break room — makeout montage, Ian notices",
  "moment-028": "Nicky's bedroom — yearbook / how-we-met montage",
  "moment-029": "Restaurant date — homeroom origin story",
  "moment-030": "Bear's bedroom — sex, “that was amazing baby”",
  "moment-031": "Bear's bedroom (3am) — Nicky watching him sleep",
  "moment-032": "Bear's living room — goodbye before work",
  "moment-033": "Mandy's inventory — Sarah confronts Bear about Nicky",
  "moment-034": "Mandy's parking lot — Ian bums a ride",
  "moment-035": "Bear's car — Ian tells Bear to stay away from Nicky",
  "moment-036": "Bear's house — vomit-covered Nicky comes home",
  "moment-037": "Ian's kitchen — pre-party, “co-dipshit”",
  "moment-038": "Ian's living room — party, drunk Jenga",
  "moment-039": "Bear's car — driving injured Nicky",
  "moment-040": "Hospital — Nicky refused (informed consent)",
  "moment-041": "Bear's house — Nicky grabs his hand going inside",
  "moment-042": "Bear's dining table — fight after the hospital",
  "moment-043": "Bear's bedroom — Nicky asks Bear to kill her",
  "moment-044": "Bear's living room — Bear sneaks out",
  "moment-045": "Franklin Park — Bear meets Sarah at her SUV",
  "moment-046": "Sarah's SUV — Sarah asks what's going on with Nicky",
  "moment-047": "Mandy's back alley — Sarah's body in the tuba case",
  "moment-048": "Mandy's break room — Nicky tapes up the tuba case",
  "moment-049": "Viewpoint — sunrise, Sarah's art-school letter",
  "moment-050": "Bear's car — screaming drive at sunrise",
  "moment-051": "Crystal shop — Bear storms in for Willows",
  "moment-052": "Crystal shop — buys the last One Wish Willows",
  "moment-053": "Crystal shop parking lot — leaves with three boxes",
  "moment-054": "Ian's house — Bear shows up unannounced",
  "moment-055": "Ian's house — Bear explains the wish, gives Ian a Willow",
  "moment-056": "Ian's doorstep — Bear walks out, money falls",
  "moment-057": "Bear's house — empty driveway, Willows in hand",
  "moment-058": "Bear's living room — shrine, wish that Nicky doesn't love him",
  "moment-059": "Bear's bathroom — locks Nicky out",
  "moment-060": "Bear's living room — final kiss, Bear dies",
};

export function getMomentLabel(momentId: string): string | undefined {
  return MOMENT_LABELS[momentId];
}
